<?php

namespace UNAM\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoRepository extends EntityRepository
{
    public function getPagosPorGrupo($grupo, $year){
        $em = $this->getEntityManager();
            $consulta = $em->createQuery(
                "SELECT p "
                . "FROM UNAMAppBundle:Pago p "
                . "JOIN p.grupo g "
                . "JOIN p.alumno a "
                . "JOIN g.curso c "
                . "JOIN g.maestro m "
                . "JOIN c.nivel n "
                . "WHERE g.id=:grupoId "
                . "AND YEAR(g.fechaInicio)>=:year "
                . "ORDER BY g.grupo, g.fechaInicio ASC");
            $consulta->setParameters(array(
                'grupoId'=>$grupo->getId(),
                'year'=>$year
            ));
       $resultados =  $consulta->getResult();
       return $resultados;
    }
	
	public function getGruposPorCurso($curso){
        $em = $this->getEntityManager();
            $consulta = $em->createQuery(
                "SELECT g "
                . "FROM UNAMAppBundle:Grupo g "
                . "JOIN g.curso c "
                . "WHERE c.id!=:cursoId "
                . "ORDER BY c.nombreCurso ASC");
            $consulta->setParameters(array(
                'cursoId'=>$curso->getId()
            ));
       $resultados =  $consulta->getResult();
       return $resultados;
    }
	
	public function getAlumnosPorNoGrupo($grupo){
        $em = $this->getEntityManager();
            $consulta = $em->createQuery(
                "SELECT a "
                . "FROM UNAMAppBundle:Alumno a "
                . "JOIN a.pagos p "
                . "JOIN p.grupo g "
                . "WHERE g.id!=:grupoId "
                . "ORDER BY a.nombre, a.identificacion ASC");
            $consulta->setParameters(array(
                'grupoId'=>$grupo->getId()
            ));
       $resultados =  $consulta->getResult();
       return $resultados;
    }
    
    public function getGruposPorNombre(){
        $em = $this->getEntityManager();
            $consulta = $em->createQuery(
                "SELECT DISTINCT g.grupo "
                . "FROM UNAMAppBundle:Grupo g "
                . "ORDER BY g.grupo ASC");
       $resultados =  $consulta->getResult();
       return $resultados;
    }
}
