<?php

namespace UNAM\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaestroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestroRepository extends EntityRepository
{
    public function getPagosPorMaestro($maestro, $year){
        $em = $this->getEntityManager();
            $consulta = $em->createQuery(
                "SELECT p "
                . "FROM UNAMAppBundle:Pago p "
                . "JOIN p.grupo g "
                . "JOIN p.alumno a "
                . "JOIN g.curso c "
                . "JOIN g.maestro m "
                . "JOIN c.nivel n "
                . "WHERE m.id=:maestroId "
                . "AND YEAR(g.fechaInicio)>=:year "
                . "ORDER BY g.grupo ASC");
            $consulta->setParameters(array(
                'maestroId'=>$maestro->getId(),
                'year'=>$year
            ));
       $resultados =  $consulta->getResult();
       return $resultados;
    }
}
