curso:
    path:     /
    defaults: { _controller: "UNAMAppBundle:Curso:index" }

curso_show:
    path:     /{id}/show
    defaults: { _controller: "UNAMAppBundle:Curso:show" }

curso_new:
    path:     /{idAlumno}/new
    defaults: { _controller: "UNAMAppBundle:Curso:new" }

curso_create:
    path:     /create
    defaults: { _controller: "UNAMAppBundle:Curso:create" }
    requirements: { _method: post }

curso_edit:
    path:     /{id}/edit
    defaults: { _controller: "UNAMAppBundle:Curso:edit" }

curso_update:
    path:     /{id}/update
    defaults: { _controller: "UNAMAppBundle:Curso:update" }
    requirements: { _method: post|put }

curso_delete:
    path:     /{id}/delete
    defaults: { _controller: "UNAMAppBundle:Curso:delete" }
    requirements: { _method: post|delete }
