nivel:
    path:     /
    defaults: { _controller: "UNAMAppBundle:Nivel:index" }

nivel_show:
    path:     /{id}/show
    defaults: { _controller: "UNAMAppBundle:Nivel:show" }

nivel_new:
    path:     /new
    defaults: { _controller: "UNAMAppBundle:Nivel:new" }

nivel_create:
    path:     /create
    defaults: { _controller: "UNAMAppBundle:Nivel:create" }
    requirements: { _method: post }

nivel_edit:
    path:     /{id}/edit
    defaults: { _controller: "UNAMAppBundle:Nivel:edit" }

nivel_update:
    path:     /{id}/update
    defaults: { _controller: "UNAMAppBundle:Nivel:update" }
    requirements: { _method: post|put }

nivel_delete:
    path:     /{id}/delete
    defaults: { _controller: "UNAMAppBundle:Nivel:delete" }
    requirements: { _method: post|delete }
