usuario:
    path:     /
    defaults: { _controller: "UNAMAppBundle:Usuario:index" }

usuario_show:
    path:     /{id}/show
    defaults: { _controller: "UNAMAppBundle:Usuario:show" }

usuario_new:
    path:     /new
    defaults: { _controller: "UNAMAppBundle:Usuario:new" }

usuario_create:
    path:     /create
    defaults: { _controller: "UNAMAppBundle:Usuario:create" }
    requirements: { _method: post }

usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "UNAMAppBundle:Usuario:edit" }

usuario_update:
    path:     /{id}/update
    defaults: { _controller: "UNAMAppBundle:Usuario:update" }
    requirements: { _method: post|put }

usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "UNAMAppBundle:Usuario:delete" }
    requirements: { _method: post|delete }
